### ISSUE TITLE
[Feature request] Crucibles should work like the composting barrel.

### ISSUE THREAD

**Issue by Rencer** [Unarelith/FromScratch#1]
I'm aware of that, that in this current state FromScratch is just a port of ExNihilo.
But I already saw on the Minetest forum, that; "...some gameplay elements will probably change."

I suggest to change how the crucibles work, because (like in ExNihilo) it is very confusing and even it have some issues. They should work, like the barrel works, with the leaves when you compost them to make dirt.

Example 1:
The crucible that makes lava. You can only add (maximum) 8 cobble at a time, and after some time that melts down and you can see some lava in the bottom. But in this stage that isn't really lava or anything, because you can't pick it up right now. You have to add more cobble, wait again until those melt down too, and than you can grab a bucket of lava.
IMO, this method is just really-really bad. Confusing, because you can think there is lava in the crucible that you can grab, but not. Confusing because there is nothing that indicates how much cobble I already added. Sometimes if I add more cobble it turns almost immediately to lava, but still can't pick up, because I need to add even more to form a full bucket of lava.
This whole thing doesn't make any sense, or at least I can't figured it out, since ExNihilo come out, how this stupid thing works.
This method is just isn't good, especially in the early stage of "skyblocking" when every piece of cobble is so precious, that you just need dump who-knows-how-much cobble into the crucible until it finally decide to form a bucket of lava.

It must be way much better if the crucible works like the composting barrel:
-Shows how the crucible fills up with cobble, as we can see it with the dirt in the barrel.
-Let us drop all the cobblestone that required to form a bucket of lava in one go.
-Don't start the melting process until we add all the cobblestone that forms a bucket of lava, like how the composting works.
-If we remove the bucket of lava, don't show lava in the bottom, because there is nothing in the crucible, we just grabbed it, again like how the composting works.

Example 2:
It's the wooden crucible that makes water.
I don't repeat the same things that I mentioned in my lava-crucible example, because everything is the same here.
Rather, I mention the issues that I found with wooden crucible.
I placed as much leaves into it as it is possible. After few seconds later it is possible to put even more leaves into the crucible while still no water. I waited some more time, and all that I saw that there is still now water, just the leaves, so I added more. I run out of leaves, and I thought I already added enough to form a bucket of water. So I waited. And waited. For several in-game days, but all that I saw is just leaves in the wooden crucible. At this point I thought the wooden crucible isn't working. For curiosity I clicked on the crucible with a bucket, and it filled up with water. I can grab 2 buckets, and the crucible just still shows the leaves. 
It doesn't make any sense. How this wooden crucible works is just even worst than how the lava-crucible works.
So, I suggest, like with the other crucible it must work like the compost barrel.
-Shows how it fills up with leaves.
-Let us add all the leaves that form a bucket of water in one go and no more than that.
-Don't even start to make water until enough leaves added to form a complete bucket of water.
-And of course don't show water in the crucible when it is removed.

I don't know how much bucket of lava/water the crucible can hold, but I don't see any reason that it should hold more than one bucket, because (IMO) it isn't the place where we should store our unused lava/water. They aren't tanks for holding liquids, but "machines" that make those liquids.
When I played somekind of a skyblock pack in Minecraft, I always and immediately as they formed, I removed them with a bucket and stored them elsewhere, like in buckets in a chest or made a large pit and pour them out there, or in tanks that are designed to store liquids.
In early game, we don't really need more than a few buckets of those liquids and that we can grab manually.
Especially in later game when all this lava/water making is automated, players tend to remove the formed lava/water immediately, and used them or stored them for later usage. And you can't remove liquids faster than they form, and they form in buckets that you can remove. If those liquids is not enough to make a full bucket you can't remove them. So there is really no reason to this there-is-some-but-useless amounts and left-overs to be in the crucible. Just have one bucket liquid in the crucible when it is ready, or show cobble/leaves until they finish, and show a completely empty crucible when we removed the liquid.

So, I think there is really no reason for this crucibles to hold more than a bucket of liquid.
And no need to work like this complicated and incomprehensible way like they work now.
They must be as simple to use and easy to track the progress as with the composting.

I like to request that the crucibles should work and act like the composting barrel; 
-Possible to add all (and no more until it finishes the process!) the materials that form the complete bucket of liquid.
-They can hold only one bucket worth of liquid, that when we remove, the crucible turns empty, and we see nothing in the crucible.

**Comment by Unarelith** [comment]
Ok I understand you, however FromScratch will start by being an exact clone of ExNihilo because that was the original goal. The issue you have is only because you'd need a mod like `Waila` in Minecraft or `witt`/equivalent in Minetest to see the amount of stuff in the crucible. That is not related to FromScratch (even if some balancing will come later, obviously, 9+ cobblestone for no bucket of lava is a bit too rough) but it's related to SkyFactory and its mods. It'll be fixed in a next version of Skyfactory and I'll edit the README here to tell people to use `insert-whatever-info-mod` to see how much lava/cobble is in the crucible.

I leave this issue open to remind me to do it, but the mechanics won't change.

**Comment by Rencer** [comment]
Ok, I understand. The only problem,that I really-really can't stand any of those mods like Waila or else. I hate them. I play Minecraft since beta, and only playing modded MC since beta 1.8. I know most of the mods how they work and what is what. I don't need anything that show me what I already know. For me all those mods are I't just annoyingly flasing texts that covers large part of the screen.
I understand that you like to do an exact Ex-Nihilo copy in Minetest, and it's great.
Fixing those what I menioned, give us the opportunity to play flawlessly without Waila or similar.
If you look on Youtube, you can find a bunch of Youtubers, whom play Minecraft, that they don't use Waila.
But  I can accept what and how you like to go with your mod. Thanks anyway.

**Comment by Unarelith** [comment]
I'm sorry, what? I've never seen a YouTuber playing a big modded Minecraft pack without using Waila or any similar mod.

It's not flashing, nor covering a large part of the screen, idk what you're talking about. And more important, you can configure it to make it display smaller with transparent background, so what you say is really irrelevant.

Moreover, this kind of info mod is really useful to know how many liquid you have in a tank, or how many energy you have in a machine/battery. It also allows you to know what block you're looking at, and it's really practical when you don't know every mod you're playing with. I really don't imagine possible playing without one, because there is so much information not available without it.

I understand that it could be better to allow playing the mod without it, but it's definitely not practical, and it's the same if you try to play ExNihilo without a Waila-like mod.

**Comment by Rencer** [comment]
Ok, it's your mod, game, addon (or whatever confusing name Minetesters use for their mods) you have the right to do whatever you want with it.

It is not my fault, that you like that (IMO!) useless, annoying waila.
It **does not teach you** how to play with a mod that you never saw before, even if it is tells a lot about that block. If you doesn't know that mod and what that block actually doing, it will not teach you. It's a fact. Period. You HAVE to look at other sources to learn the mod: like reading the manual online or watch some tutorial videos or somthing like that.

>configure it to make it display smaller with transparent background, so what you say is really irrelevant.

Seriously? It doesn't metter if you turn it transparent, IT'S STILL THERE! It's still falshing those text and box quicly and it is as annoying as without transparency, so what you say is really irrelevant.

>I understand that it could be better to allow playing the mod without it, but it's definitely not practical, and it's the same if you try to play ExNihilo without a Waila-like mod.

Well..what can I say about this. Am I really want to be even react to this sentence?
I think I have to, and I doesn't even care about that you get angry with me or not, but you need to know something! 
ExNihilo without Waila? YES! I never ever played any skyblock or similar modpack that has ExNihilo in it WITH waila, as you know it just annoys me. And skyblocking is one of my favourite; skyblocking is about FIGURING OUT how to build a large complex automated base from nothing. Skyblocking is HARDCORE. If you really know how skyblock work, if you are really true to how you should play the original skyblocks, than you never say such a stupid thing like what you posted about exnihilo and waila.
All and everyting in your last post here made me to think; that you are a very unexperinced skyblocker, or just in general about playing modded MC.
YOU need waila because, it seems, you doesn't have a clue about any of the blocks or mods that you playing with. I see it know, the reason you can't understand that someone doesn't need Waila, is beacuse you know almost nothing about the mods, and the blocks that they add to the game, that you play with.
It is EXACTLY the same BS, like if you say; that it is impossible to drive a car that doesn't have a HUD.

Don't get mad! I still REALLY LIKE what you done so far. It is awesome that you ported all those mods that writen in Java, into Lua. Keep up the good work!

BUT! Your stubborness, that you doesn't even want to make a very small change, in your mod, to satisfy players that don't need waila; made me to never play with your mod again!

**Comment by Unarelith** [comment]
You're not even understanding correctly what I say.

> It does not teach you how to play with a mod that you never saw before

I never said that. I just said that it helped, because when you play modpacks with 300+ mods, you can't know every texture of every block of every mod. That's a fact actually.

Let's say I play 1.7.10 and want to move to 1.12.2, I won't know Astral Sorcery, Cyclic, Random Things, new textures for Extra Utilites 2, Embers, etc... If I never used Mekanism, I won't be able to tell "oh this texture is the crusher", "this texture is the smelter" (and Mekanism machines still confuses me even now, however I can recognize all Thermal Expansion machines by just looking at them).

And as I said, such a mod is also useful to know the amount of liquid in a tank, the amount of energy in a cell, the growth of a crop (Pam's Harvestcraft adds so many crops you cannot just remember all the texture for the full grown crops, so without waila you'll just randomly right-click the crops).

> It does not teach you how to play with a mod that you never saw before, even if it is tells a lot about that block. If you doesn't know that mod and what that block actually doing, it will not teach you. It's a fact.

> You HAVE to look at other sources to learn the mod: like reading the manual online or watch some tutorial videos or somthing like that.

Yep, and I agree with you, I never said the opposite. But having the name of the block/mod to make an online search is easier than just typing "minecraft mod white block with blue spots".

> Seriously? It doesn't metter if you turn it transparent, IT'S STILL THERE! It's still falshing those text and box quicly and it is as annoying as without transparency, so what you say is really irrelevant.

Well, the box is transparent, so it isn't flashing, you're the one being irrelevant here. And yes the text is flashing, but like I said, it's still possible to reduce its size to be less annoying. I'm sure there's even a possibility to trigger its display by holding shift, so that it's only on the screen when you press shift.

>  If you really know how skyblock work, if you are really true to how you should play the original skyblocks, than you never say such a stupid thing like what you posted about exnihilo and waila.

The original skyblocks? You mean vanilla skyblocks? I don't care having Waila on a vanilla skyblock because I already know all the blocks since there's not many of them, and the texture is always self-explanatory.

> All and everyting in your last post here made me to think; that you are a very unexperinced skyblocker, or just in general about playing modded MC.
> YOU need waila because, it seems, you doesn't have a clue about any of the blocks or mods that you playing with. I see it know, the reason you can't understand that someone doesn't need Waila, is beacuse you know almost nothing about the mods, and the blocks that they add to the game, that you play with.

Ok so now you're going ad-hominem and I really don't like that. It's not just me, it's the majority of the modding community that think Waila is an useful mod. I play modded minecraft since the 1.5, and I never, never, never heard someone complain about this mod.

I'm experienced about playing modded MC, I'm just not experienced with all the mods I use when I play, and that's the best part of midding MC, discovering things. If I already know each block of each mod I'm using, then what's the point? That's why I like playing big modpacks and that's why I like to play with Waila to actually know what I'm looking at.

> It is EXACTLY the same BS, like if you say; that it is impossible to drive a car that doesn't have a HUD.

And that's kinda true if you consider the speed display and the gas display to be the actual HUD. How can you drive a car without knowing at which speed you are? How do you know how long you can drive without knowing how much gas you have left? See how stupid this comparison is?

Joke aside, I never said Waila was a must-have, I just said that I couldn't play without it. And a lot of people think like me. But I don't blame you if you don't.

> BUT! Your stubborness, that you doesn't even want to make a very small change, in your mod, to satisfy players that don't need waila; made me to never play with your mod again!

Then never play with it again, I don't care. You're being childish with your CAPSLOCK things, and the way **you** are stubborn with I DON'T WANT WAILA IT'S FLASHING I HATE IT.

This mod will definitely improve a little bit the way dry dirt looks compared to compost, like ExNihilo did. But it'll still be unclear, even though it'll be visible. And btw I'm colorblind so in ExNihilo, I don't see much the difference between dry dirt and compost.

So what I'm saying since the beginning is that, to have a better understanding of the content of the blocks, a mod like Waila could make things easier, and this is the solution I'm going to use.
